### ISSUE TITLE
cut off 95%

### ISSUE THREAD

**Issue by thibaulttabarin** [hdr-bgnn/Morphology-analysis#11]
In the analysis the cutoff is 95% of the biggest blob for a trait to be retained.
If the trait is not retain and necessary for the rest of the analysis it create problems
in this case , the eye of the fish is excluded, /fs/ess/PAS2136/BGNN/Minnows/Segmented/INHS_FISH_23706_segmented.png
I feel the cut off is to restrictive.
Or we need a criteria to remove fish using the presence matrix.
This need to be clarified

**Comment by meghalithic** [comment]
@thibaulttabarin what results are you getting that they're too restrictive? I have >4K images after retaining images with all traits at 95%. The code is [here](https://github.com/hdr-bgnn/minnowTraits/blob/main/Scripts/selectionCriteriaSegmentedImages.R). Let me know if you're getting different results!

**Comment by thibaulttabarin** [comment]
I see, there are plenty of fish to play with, you are right, but in the last run with the 95% cut off I was fixing bug I got with around 60 images and realize that some had the small patch of eye in the caudal fin that were about 8% of the main eye like here
/fs/ess/PAS2136/BGNN/Minnows/Segmented/INHS_FISH_23706_segmented.png

**Comment by thibaulttabarin** [comment]
We choose 60% for the moment
