### ISSUE TITLE
change HD

### ISSUE THREAD

**Issue by meghalithic** [hdr-bgnn/Morphology-analysis#12]
If HD goes from landmark 2 to 13, keep the same
If HD goes through the midline of the eye, change to HH

**Comment by thibaulttabarin** [comment]
What HH stand for? Head Height

**Comment by thibaulttabarin** [comment]
I would change HH to HH_lm because we use landmark of the eye center to calculate this one

**Comment by meghalithic** [comment]
I will do this to v1
