### ISSUE TITLE
Add measurements types to readme

### ISSUE THREAD

**Issue by meghalithic** [hdr-bgnn/Morphology-analysis#18]
Add and explain the four measurement types to the readme as they relate to the functions in BGNN_Snakemake:
1. using landmarks
2. using bbox
3. area
4. angle

**Comment by thibaulttabarin** [comment]
#22

**Comment by meghalithic** [comment]
@thibaulttabarin do we want to make something similar to part 3 in the readme for the functions "measure_lm", "measure_bbox", etc.?

**Comment by meghalithic** [comment]
@thibaulttabarin all the rescaling of the image occurs before landmarks and measurements are extracted, correct? All that information is in BGNN_Snakemake (or rather will be)?

**Comment by thibaulttabarin** [comment]
tag version corresponding to the question
https://github.com/hdr-bgnn/BGNN-trait-segmentation/releases/tag/0.0.5
1 - Rescaling is more a resizing to the original size of the cropped images used as an input to maruf's Traits-segmentation
2 - the Resizing happen in the Segmentation_main.py https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/5dc0ab34201ac2b715e784849acdb2a38e962da5/Segment_mini/scripts/segmentation_main_rescale_origin.py#L92-L95
3- In the output folder Segmented/ (on OSC) containing the output form Maruf, all the segmented images are resize to original cropped size

Those information need to be concluded in the documentation

**Comment by meghalithic** [comment]
I'll make an issue for that on BGNN_Snakemake
