### ISSUE TITLE
Update landmarks description

### ISSUE THREAD

**Issue by thibaulttabarin** [hdr-bgnn/Morphology-analysis#26]
create a column code_definition in https://github.com/hdr-bgnn/Morphology-analysis/blob/main/Traits_description/Minnow_Landmarks%20_v1.csv

This column should describe how we identify the landmarks (i.e. most anterior of the bbox)

**Comment by meghalithic** [comment]
- remove "type"
- combine terminology and position (definition)
- change column names to naming convention
- add column for ontology axiom
- make column names the same for measurement and landmarks

**Comment by megbalk** [comment]
e.g., 1, 2, 13 all based on the head

**Comment by meghalithic** [comment]
@thibaulttabarin all changes are on branch issue-26. Just need to fill in "Code_Definition" column.
