### ISSUE TITLE
update the traits description

### ISSUE THREAD

**Issue by thibaulttabarin** [hdr-bgnn/Morphology-analysis#9]
Check measurements and landmarks list and map
Make sure that we have 1-18 landmarks in Traits_description/landmarks_v1.png (correspond to the version 1 for the future release of Morphology-analysis).
Add corresponding landmarks cvs Traits_description/landmarks_v1.csv with correct description.

Add the measurements in Traits_description/measurments_v1.png image with measurements
Add the measurements in Traits_description/measurments_v1.csv description of the measurement

**Comment by meghalithic** [comment]
addressed in PR #17
